---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-source
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./app
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: app-source
  targetNamespace: from-flux-ns
  timeout: 3m0s
  wait: true
