---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-source
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./app # directory of https://github.dev/vermavarun/flux-source from where the deployment should happen
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: app-source
  targetNamespace: default
  timeout: 3m0s
  wait: true
